version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - tempo
      - promtail
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    labels:
      - "logging=promtail"
    logging:
      driver: "json-file"

  loadgen:
    build:
      context: .
      dockerfile: loadgen.Dockerfile
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "4318:4318"
      - "4317:4317"
      - "9095:9095"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo/traces
    command: [ "-config.file=/etc/tempo.yaml" ]

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  tempo-data:
